### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by rhurley46** [rhurley46/GolfWebApp#1]
TODO:

- [ ] Create basic webapp
- [ ] Create upload functionality
- [ ] Connect to s3 with boto3
- [ ] Send csv upload to s3 bucket
- [ ] Trigger Glue job to do etl
- [ ] Query database from boto3 in app
